/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tampilan;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Version = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BoxNama = new javax.swing.JTextField();
        login = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(53, 11, 133));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("YudaAR Computer");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 20, 218, 29);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("\"Menerima Pesanan Kostum Rakitan PC Komputer\"");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 50, 300, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 80);

        Version.setForeground(new java.awt.Color(255, 255, 255));
        Version.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Version.setText("Project Version 1.0");
        getContentPane().add(Version);
        Version.setBounds(10, 380, 120, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nama Pemesan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 140, 140, 14);

        BoxNama.setBackground(new java.awt.Color(0, 0, 0));
        BoxNama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BoxNama.setForeground(new java.awt.Color(255, 255, 255));
        BoxNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BoxNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxNamaActionPerformed(evt);
            }
        });
        getContentPane().add(BoxNama);
        BoxNama.setBounds(150, 170, 200, 30);

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login_blue.png"))); // NOI18N
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(200, 210, 100, 43);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/background-index.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxNamaActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        if(BoxNama.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Nama tidak boleh kosong!", "Kesalahan", JOptionPane.WARNING_MESSAGE);
            login.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Berhasil Login!");
            JOptionPane.showMessageDialog(this,"Selamat Datang, "+BoxNama.getText());
            login.setVisible(false);
            FormList n = new FormList();
            n.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BoxNama;
    private javax.swing.JLabel Version;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    // End of variables declaration//GEN-END:variables
}
